# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Automatic-Healthy-Report

on:
  push:
    branches: 
    - main
  schedule:
    - cron: 17 1 * * * 
    - cron: 19 7 * * *

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Fxxk_SUES

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
      with:
        ref: main
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install beautifulsoup4
        pip install lxml
    
    - name: Run
      run: python auto-do.py ${{ secrets.NUM }} ${{ secrets.PWD }}
      
    - name: Sending message
      uses: yakumioto/serverchan-action@v1
      with:
        key: ${{ secrets.sckey }}
        text: 体温提交情况
        desp: 消息内容
