# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Automatic-Healthy-Report

on:
  push:
    branches: 
    - main
  schedule:
    - cron: "15 0 * * *" 
    - cron: "20 1 * * *"
    - cron: "25 6 * * *"
    - cron: "30 7 * * *"  

jobs:
  build:
    runs-on: ubuntu-latest
    name: Happy-Report

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
      with:
        ref: main
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install beautifulsoup4
        pip install lxml
    
    - name: Run and send message
      run: python auto-do.py ${{ secrets.NUM }} ${{ secrets.PWD }}

