# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Health-Report-Master 

on:
  push:
    branches: 
    - master
  schedule:
    - cron: "15 23 * * *" 
    - cron: "25 5 * * *"  

jobs:
  build:
    runs-on: ubuntu-latest
    name: Fxxk_SUES

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
      with:
        ref: master
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install beautifulsoup4
        pip install lxml
        pip install pyTelegramBotAPI
    
    - name: Run and send message
      run: python auto-do.py ${{ secrets.NUM }} ${{ secrets.PWD }} ${{ secrets.SCKEY }} ${{ secrets.BOT_TOKEN }} ${{ secrets.CHAT_ID }}
     
    - name: Fail feedback
      if: ${{ failure() }}
      run: python fail-feedback.py ${{ secrets.SCKEY }} ${{ secrets.BOT_TOKEN }} ${{ secrets.CHAT_ID }}
